language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - composer install --dev --prefer-source
  - php -S localhost:8080 -t web web/dispatch.php & # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
script:
  - php vendor/behat/behat/bin/behat
  - php vendor/phpspec/phpspec/scripts/phpspec.php spec